#!/usr/bin/env bash

##############################################################################
# setup_azuracast_install
##############################################################################

# Clone AzuraCast Stable Branch.
#
# To make sure, that this installer will always work, this is not AzuraCasts default Stable branch.
# Its the same codebase as the Original.
#
# But i will make sure, that anything is working before updateing to latest stable version.
# If you want, you can change it to its original. But you shouldnt ask for help in this case.

# Get required files
if [ "$azuracast_git_version" = "stable" ] || [ "$azuracast_git_version" = "rolling" ]; then
    su azuracast <<EOF
git clone https://github.com/scysys/AzuraCast.git /var/azuracast/www
git -C /var/azuracast/www checkout -f ${set_azuracast_version}-org
composer --working-dir=/var/azuracast/www install --no-dev --no-ansi --no-interaction
EOF
else
    su azuracast <<EOF
git clone https://github.com/scysys/AzuraCast.git /var/azuracast/www
git -C /var/azuracast/www checkout -f ${set_azuracast_version}-scy
composer --working-dir=/var/azuracast/www install --no-dev --no-ansi --no-interaction
EOF
fi

# Directories 0755
find /var/azuracast/www -type d -exec chmod 755 {} \;

# Files 0644
find /var/azuracast/www -type f -exec chmod 644 {} \;

# Popluate env.ini
echo "
;
; AzuraCast Environment Settings
;
; This file is automatically generated by AzuraCast.
;

[configuration]
application_env = production
MYSQL_HOST = localhost
MYSQL_PORT = 3306
MYSQL_USER = azuracastMySQLUsername
MYSQL_DB = azuracastMySQLDatabase
MYSQL_PASSWORD = azuracastMySQLPassword
" >>/var/azuracast/www/env.ini

# Set right DB Password
sed -i "s/azuracastMySQLDatabase/$set_azuracast_database/g" /var/azuracast/www/env.ini
sed -i "s/azuracastMySQLUsername/$set_azuracast_username/g" /var/azuracast/www/env.ini
sed -i "s/azuracastMySQLPassword/$set_azuracast_password/g" /var/azuracast/www/env.ini

# CHMOD & CHOWN env.ini
chmod 0640 /var/azuracast/www/env.ini
chown azuracast.azuracast /var/azuracast/www/env.ini

# Migrate DB
supervisorctl restart redis
supervisorctl restart mariadb
php /var/azuracast/www/bin/console azuracast:setup:migrate
supervisorctl stop mariadb

# Build
source azuracast/build.sh

# /etc/security/limits.conf
source azuracast/ulimit.sh || { echo "Error sourcing ulimit.sh"; exit 1; }

# Logs
source azuracast/logs.sh || { echo "Error sourcing logs.sh"; exit 1; }
